##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: CleanArquitecture
  data:
    mongodb:
      uri: mongodb+srv://experimentaly:experimentaly2021@cluster0.ctcza.mongodb.net/almacen?retryWrites=true&w=majority
      database: almacen